language: generic
services:
  - docker
env:
  - MAPBOX_TOKEN=$MAPBOX_TOKEN
jobs:
  include:
  - stage: deploy
    name: "docker hub"
    before_script:
      - docker pull "$IMAGE_NAME" || true
      - major=0
      - version=$major.$TRAVIS_BUILD_NUMBER
    script:
      - docker build --pull --build-arg MAPBOX_TOKEN="$MAPBOX_TOKEN" --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
    before_deploy:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
      - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
    deploy:
      provider: script
      script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
      on:
        all_branches: true
